### ISSUE TITLE
Debouncing button to D2

### ISSUE THREAD

**Issue by martinsg88** [firefly/wallet#3]
Just wanted to say I really like the project, very cool use of an arduino (or microcontroller in general). 

Though if you would allow me, I have a question about your schematic. I see that you have a pull-down resistor to D2, however I am wondering what the input noise is like. It doesn't look like you are debouncing in hardware. Is this something you are solving in software? It seems like it would be more appropriate to add a 0.1uF capacitor as well?

**Comment by ricmoo** [comment]
Sounds like you are far more an electronics person than I, especially in the analog circuits department.

Any suggestions you have would be greatly welcome, and I will research that.

For the Firefly, debouching shouldn't really be an issue since the button is at most ever pushed once, and the moment it gets a high signal, nothing else really matter, it never reads the button again.

**Comment by martinsg88** [comment]
I deeply apologize for keeping this open this long. 
Thanks again for the kind response.
