### ISSUE TITLE
Support for any regular ERC-721 token. 

### ISSUE THREAD

**Issue by eulphean** [firefly/wallet#9]
Hey guys!

Thanks a lot for putting this project together. I wanted to ask you if I can use this wallet to sign and store a regular ERC-721 token (other than a cryptokitty). I presume I'll have to implement the standard functions as per the spec and minting the token myself, but how would I transfer that token to this wallet? Will I use an app like Ethers, metamask, etc.

**Comment by ricmoo** [comment]
Absolutely! The wallet works with any Ethereum transaction, regardless of whether it is for simply sending ether or calling a specific contract. We have some exciting new features coming out soon though, that will make it really "pop" for ERC-721 tokens. :)

The wallet has an Ethereum address, you can just transfer the token to that address. Make sure there is a dapp you can load to transfer the token though, that works through Ethers Wallet, since we haven't added generic ERC-20 and ERC-721 support to Ethers Wallet. That too is coming soon. :)

**Comment by eulphean** [comment]
Great. Thanks for your response Richard.
